# Use postgres/example user/password credentials
version: '3.1'
services:
  db:
    container_name: hello_couchDB
    image: couchdb:latest
    restart: always
    ports:
      - 5984:5984
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: password
