# Use postgres/example user/password credentials
version: '3.1'
services:
  db:
    container_name: hello_postgres
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example #default user name "postgres"
  adminer:
    image: adminer
    restart: always
    ports:
      - 9876:8080
